### ISSUE TITLE
Feasible to implement this without using Rust, but with C/C++/Fortran?

### ISSUE THREAD

**Issue by barracuda156** [oxfordcontrol/clarabel-r#12]
It cannot be done without depending on Rust, can it? Rust has an abysmal cross-platform support (i.e. just broken on a number of platforms completely, newer versions of it broken on some other).

**Comment by bnaras** [comment]
@barracuda156 can you provide details on your platform? The CRAN docs indicate that at least for the three major platforms Rust is supported but I realize that cannot possibly cover all situations/constraints.

**Comment by barracuda156** [comment]
> @barracuda156 can you provide details on your platform? The CRAN docs indicate that at least for the three major platforms Rust is supported but I realize that cannot possibly cover all situations/constraints.

AFAIK, current version of Rust (i.e. `rustc`) does not build on any macOS < 10.13 (which leaves _all_ powerpc and i386 broken, and a large chunk of x86_64).

`rustc` is currently broken on OpenBSD on PowerPC.
On FreeBSD it seems to kinda work on ppc, but there are struggles: https://github.com/rust-lang/rust/issues/116845

These are systems I am familiar with, but generally `rustc` will not work on any platform which is not supported by current LLVM (at least until GCC backend is complete and working). Plus platforms where LLVM works, but `rustc` itself is broken.

CRAN only cares about a few select platforms in bleeding edge versions on mainstream archs.

A separate concern is that Rust is simply a ridiculously heavy dependency to require for someone who does not need it otherwise. This applies to any platform.

**Comment by goulart-paul** [comment]
I'm not sure I understand what you are asking for here.   is the request for us to *completely reimplement* this project in C or Fortran?   

The solver is written in Rust.   As with any choice of development language, that decision comes with pros and cons including the range of platforms supported.    The list of supported platforms for Rust is [here](https://doc.rust-lang.org/nightly/rustc/platform-support.html).   If you don't find your platform there, then this solver is not a good option for you.

If you want a solver with similar functionality but in C, then any of ECOS, SCS or OSQP or might be choices depending on the particular class of problem you want to solve.

**Comment by barracuda156** [comment]
@goulart-paul Thank you for responding. Of course, if the whole of the code is in Rust, then the only chance of getting to compiled on every system will be `gccrs`, when/if it is usable. Understandably, no one will switch the language for the sake of a tiny share of potential users.

The context on my question was the following: there are projects which require Rust currently (FireFox, some Python cryptography packages, a few Gnome ports), but it was used to add some functionality and rewrite specific parts, and all of those do have rust-free versions (dating back a few years, but totally usable), and current versions could be modified to use rust-less codepaths, at least in principle. Adding Rust was in some cases gradual, so there were some releases where it could still be turned off manually (`pycryptography`, as I recall). Projects of this kind can be switched away from Rust, the obstacle being only a lack of willingness from their upstreams.
