### ISSUE TITLE
update interface to v0.5.0

### ISSUE THREAD

**Issue by goulart-paul** [oxfordcontrol/clarabel-r#4]
We have released v0.5.0 of the Rust solver code, which supports SDPs when BLAS/LAPACK are available.    I suspect that getting that to work with this package will be done most easily by linking directly to whichever BLAS/LAPACK libraries are already used by R rather than by relying on a dependency like openblas.  

It may be necessary to modify the main repo to support this, through introduction / modification of features in the Cargo.toml and / or adding a build script to do the linking.  Happy to help with that.

Is there some environment variable supplied by R that points to the right libraries?

**Comment by bnaras** [comment]
@goulart-paul, thank you.  I'll take a look at this as soon as I can.

**Comment by bnaras** [comment]
Just an update.  I finished rolling up a crate [r-blas-lapack-src](https://github.com/bnaras/r-blas-lapack-src) that I hope to publish soon. This will provide blas and lapack via R. If all goes through, all I would then need is a feature to be added to Clarabel.rs  say
```
sdp-r = ["sdp", "blas-src/r-blas-lapack-src"] 
```
to finish off the update. (I'm trying to make it all available in the same place as `blas-src` and `lapack-src`.)

**Comment by bnaras** [comment]
Closing this issue as completed. Also added a [PSD example](https://oxfordcontrol.github.io/clarabel-r/articles/clarabel.html)
