### ISSUE TITLE
Add support for generalized power cones

### ISSUE THREAD

**Issue by goulart-paul** [oxfordcontrol/clarabel-r#7]
We have released Clarabel v0.6.0 with support for generalized power cones.   Will need to port the additional cone constraint to R before updating to a new release.   The new cone type is defined in Eq (15a) of this paper: https://arxiv.org/pdf/2305.12275.pdf
 
NB - The new cone type takes two parameters: 1) a vector of floats and 2) a nonnegative integer.    The length of the vector argument corresponds to the dimension $d_1$ in the paper above.   The second argument provides $d_2$.

**Comment by bnaras** [comment]
Sorry for the delay, but I've now rolled up version 0.9.0 and it is on CRAN now. Passes all the applicable tests in Clarabel.rs.

**Comment by bnaras** [comment]
Closing this issue as completed.
